### ISSUE TITLE
Error in Android 4.4.4 when making https request

### ISSUE THREAD

**Issue by IJRS** [nativescript-community/https#12]
When I make a request on a device running Android 5.0.1 it works correctly but in Android 4.4.4 I get an error, any solution?
Error obtained:
Https.request error javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x72699f10: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x39fa31e3:0x00000000)

**Comment by roblav96** [comment]
@IJRS add this:
```typescript
application.android.on(application.AndroidApplication.activityCreatedEvent, function(args: application.AndroidActivityBundleEventData) {
	let policy = new android.os.StrictMode.ThreadPolicy.Builder().permitAll().build()
	android.os.StrictMode.setThreadPolicy(policy)
})
```

**Comment by IJRS** [comment]
@roblav96 

I already have integrated this function in my project, which works for android versions >= 5.0, but for versions <5.0 does not work (in my case it is the android version 4.4.4) ..
