### ISSUE TITLE
SSLPeerUnverifiedException 

### ISSUE THREAD

**Issue by kentplaza** [nativescript-community/https#13]
Need some assist. 
Why when i enabled the SSL pinning and Test HTTPS, always getting javax.net.ssl.SSLPeerUnverifiedException error message as below:

> JS: Https.request error javax.net.ssl.SSLPeerUnverifiedException: Hostname xxxx.azurewebsites.net not verified:
> JS:     certificate: sha256/nrmpk4ZI3wbRBmUZIT5aKAgP0LlKHRgfA2Snjzeg9iY=
> JS:     DN: CN=*.azurewebsites.net
> JS:     subjectAltNames: [*.azurewebsites.net, *.scm.azurewebsites.net, *.azure-mobile.net, *.scm.azure-mobile.net]

while disabled SSL, it called to api sucessfully.

Any idea?

thanks

**Comment by roblav96** [comment]
@kentplaza it looks like you're using a hostname `xxxx.azurewebsites.net` which is not in the list of verified names.

**Comment by kentplaza** [comment]
@roblav96 what do u mean "not in the list of verified names"? because the saw the cer cert is wildcard *.azurewebsites.net

**Comment by kentplaza** [comment]
@roblav96 I see, but if i double click on the cer cert. I saw the subject is *.azurewebsites.net.
![1](https://user-images.githubusercontent.com/9535716/27362543-ab3d9c2a-5661-11e7-81c3-ff7b68612a9c.PNG)

----------------------------------------------

![2](https://user-images.githubusercontent.com/9535716/27362544-ab68c5ee-5661-11e7-8062-260eaca5ef97.PNG)

**Comment by kentplaza** [comment]
@roblav96 It is work fine with exact domain. I tried on not using wildcard.

**Comment by roblav96** [comment]
@kentplaza ye currently there's no support for wildcards

**Comment by crisleiria** [comment]
I have the same problem.. Does wildcards are supported now?
