### ISSUE TITLE
NTLM support?

### ISSUE THREAD

**Issue by tigerdi** [nativescript-community/https#19]
Any chance of making this work with NTLM authentication? How can I use this with something like JCIFS (https://jcifs.samba.org/)?

**Comment by roblav96** [comment]
@tigerdi I don't believe so, not even sure what that protocol is :X

**Comment by tigerdi** [comment]
@roblav96 I can see that you have included AFNetworking in your plugin. How would I be able to use the classes belonging to AFNetworking? I was thinking I could use that in my iOS app to do NTLM authentication. For example, I would be looking to use things like `AFHTTPSessionManager`. But that doesnt seem to be exposed to the typescript intellisense. Do i need to import it somehow?

**Comment by tigerdi** [comment]
@roblav96 Forget about the above. For some reason the AFNetworking classes suddenly became visible after rebuilding the application. Thanks
