### ISSUE TITLE
iOS PUT not working

### ISSUE THREAD

**Issue by jschwartz73** [nativescript-community/https#20]
I'm having trouble getting an HTTPS PUT method to work.  Currently, the app just sort of freezes when it gets to the PUT.  

Debugging the library I found that the file node_modules/nativescript-https/https-ios.js at  approximately line 70, has an if for GET and then an else if for POST, but nothing PUT or DELETE.

I thought this was a drop in replacement for the http module.  Am I missing something?  

I installed the plugin as follows:
tns add plugin nativescript-https

Any suggestions would be greatly appreciated.

**Comment by HenryDiesel** [comment]
It seems that PUT is not supported, only POST and GET.  But okhttp3 which is being used inside the module does support PUT.  Linking the two seems like a major amount of work though.
