### ISSUE TITLE
Hostname not verified 

### ISSUE THREAD

**Issue by inane** [nativescript-community/https#28]
Hi Robert,

Thank you for your great implementation and plugin.

I am trying to connect my app to WS based in XML-SOAP but I am having the next error in the console:

JS: 'Error: javax.net.ssl.SSLPeerUnverifiedException: Hostname XX-XX-XX  not verified:
JS:     certificate: sha256//zAeFdL0ymoNZ6XuKCOGJ3FwR/lYqAhkxku0wH3SE0k=
JS:     DN: CN=localhost,OU=FOR TESTING ONLY,O=MyOrganization,L=MyTown,ST=MyState,C=US
JS:     subjectAltNames: []'

Any clue about what would it be the problem?

Thank you in advance.

**Comment by 2adi** [comment]
I have a error like you. Can you ask me any idea if you have any solution for this please?
