### ISSUE TITLE
Nativescript-https plugin issue

### ISSUE THREAD

**Issue by NickIliev** [nativescript-community/https#36]
_From @smartsanja2013 on August 23, 2018 10:36_

Highly appreciated someone can help me how to figure-out this issue. I have tried-out so many days,different certs, different domain names. nothing works.

I have to enable ssl pining in my app. So, I had to use https://github.com/gethuman/nativescript-https 1 plugin. I have follow the implementation steps correctly. But when I make the https request, iOS app crash in AFNetworking EXC_BAD_Access error. I have added two NSLogs to AFHTTPSSessionManager class.
<img width="804" alt="screen shot 2018-08-22 at 2 52 09 pm" src="https://user-images.githubusercontent.com/12458727/44520437-67ea9480-a702-11e8-88f4-5f25fbce6c5a.png">

Output
```
Securitypolicy AFSSLPinningModePublicKey
baseURL scheme (null)
```
It seems something wrong with setting the certificate and host in the angular code. By right, Securitypolicy should be AFSSLPinningModeCertificate and baseURL schme should have https.

Android app gives this error
`Https.request error javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Implementation details as bellow
reference.d.ts
```
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
```

imports
```
import { File, Folder, knownFolders, path } from 'file-system'
import * as Https from 'nativescript-https'
```

in the constructor
```
let dir = knownFolders.currentApp().getFolder('certs')
let certificate = dir.getFile('httpbin.org.cer').path
Https.enableSSLPinning({ host: 'httpbin.org', certificate: certificate});
```

method
```
clickLogin(){
        Https.request({
            url: 'https://httpbin.org/get',
            method: 'GET',
            headers: {
                'content-type': 'application/json'
            },
        }).then(function(response) {
            console.log('Https.request response', response)
        }).catch(function(error) {
            console.error('Https.request error', error)
        })
}
```

tns version 4.0.1 node v6.11.5

_Copied from original issue: NativeScript/NativeScript#6211_

**Comment by NickIliev** [comment]
@smartsanja2013 the error log seems to be related to a known bug in AFNetworking pod that is used in the iOS part of nativescript-https - the related issue is logged [here](https://github.com/AFNetworking/AFNetworking/issues/4150)

At this very moment, no solution is provided by the author of the pod - you could track the issue for any possible updates regarding this one and if a newer version of the pod is published you can re-pack the plugin to use the newer AFNetworking pod.

I've used [this test app ](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/test/httpsPlugin) to reproduce the following error:
```
*** Terminating app due to uncaught exception 'Invalid Security Policy', reason: 'A security policy configured with `AFSSLPinningModePublicKey` can only be applied on a manager with a secure base URL (i.e. https)'
```

**Comment by NickIliev** [comment]
**Possible solution:**

@smartsanja2013 try to revert the version of the AFNetwork POD to a stable one like suggested [here](https://github.com/AFNetworking/AFNetworking/issues/4150#issuecomment-367961627)

To achieve that clone the[ nativescript-https repository](https://github.com/gethuman/nativescript-https) and hardcore the pod version in [`platform/ios/Podfiler`](https://github.com/gethuman/nativescript-https/blob/master/platforms/ios/Podfile) to 3.1.0 (without using tilde ~ - check [this article for POD versioning](https://guides.cocoapods.org/using/the-podfile.html) specifics) and then do `npm pack` on the plugin source and use the newly packed plugin.

**Comment by ashokch8** [comment]
https accepts multiple certificates?

**Comment by ashokch8** [comment]
@EddyVerbruggen Hi Eddy, https accepts multiple certificates to work with multiple servers?
