### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by mariodiciccio** [nativescript-community/https#39]
Hi, i have a problem on  nativescript-https 1.0.1.

I installed plugin with _tns plugin add nativescript-https_
but when launch the app, his result is:
```
nativescript-https > Disabled SSL pinning
JS: Https.request error javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

The code is:
```
  Https.disableSSLPinning();
  Https.request({
    url: 'https://dominio.com:6943/rest/api/',
    method: 'GET',
    headers: {
      'content-type': 'application/json'
    },
}).then(function(response) {
    console.log('Https.request response', response)
}).catch(function(error) {
    console.error('Https.request error', error)
})

```
Why? Any idea?

**Comment by nmocruz** [comment]
are you using self-signed certificates? the certifcate is valid? if no.., it can be your problem, this plugin is not offering nothing to bypass ssl validation errors due invalid certificates.

**Comment by alessandraferrua** [comment]
I have the same problem, the certificate is valid. Using HTTPer work correctly. Any idea?

**Comment by luiguild** [comment]
any news about it?

**Comment by gonzalesgm-git** [comment]
got this very same issue, certifcate is valid and is working on web, but not on mobile. any workaround?

**Comment by edusperoni** [comment]
These kind of errors usually come from misconfigured servers (like missing chain certs)

There are a few tools that can validate your config, hopefully this one does the trick https://whatsmychaincert.com/
