### ISSUE TITLE
Not drop in replacement for requests that contain req body

### ISSUE THREAD

**Issue by rynop** [nativescript-community/https#43]
This lib uses [`body`](https://github.com/gethuman/nativescript-https/blob/163758362e8db61293940d128c9aa8059074c1a8/src/https.common.ts#L22) (on POST for example).

NS http lib uses [`content`](https://docs.nativescript.org/api-reference/interfaces/_http_.httprequestoptions#content)

Was this intentional or did NS lib change signature and nativescript-https just didn't keep up?

Also, I noice the request body object ([HttpsRequestObject](https://github.com/gethuman/nativescript-https/blob/163758362e8db61293940d128c9aa8059074c1a8/src/https.common.ts#L14)) only supports a map of `string` to `string|number`.  How would one post a boolean (`{"isSet":true}`) or a list (`["a","b"]`)

Thanks in advance.

**Comment by mpht** [comment]
Not sure if it works for you, but have you tried doing something like this:

````
https.request({
        method: 'POST',
        url: this.createUrl( url ),
        headers: { 'Content-Type': 'application/json' },
        body: { content: JSON.stringify(bodyObject) }
}
````

**Comment by roblav96** [comment]
`JSON.stringify({"isSet":true})`
