### ISSUE TITLE
Cannot see request content properties

### ISSUE THREAD

**Issue by leocrawf** [nativescript-community/https#46]
Can someone explain why this piece of code stopped working when I use the latest version:
   
    const http = require("nativescript-https");
    http.disableSSLPinning();
    http.request({
            url: `${config.apiURL}/circular/`,
            method: "POST",
            headers: { "Content-Type": "application/json" },
            content: JSON.stringify({
                schoolID:config.schoolID
            })
        })
in that I stopped seeing the schoolID on the server side but when I switched back to "nativescript-https": "^1.0.1" it worked as expected? The only difference is that one is the latest version while the other is version 1.0.1.

**Comment by lukesUbuntu** [comment]
any errors?

**Comment by leocrawf** [comment]
I am not seeing an error message on the client. On the server hoever, I see where the properties are not passed over.

**Comment by leocrawf** [comment]
this solved the issue: https://github.com/EddyVerbruggen/nativescript-https/issues/44
