### ISSUE TITLE
Request Timeout 

### ISSUE THREAD

**Issue by bobbyngwu** [nativescript-community/https#48]
Thanks for the plugin. It may be helpful to allow a timeout property in the HttpRequestOptions interface to be used to override the okhttp3 Request default 10 seconds timeout

**Comment by EddyVerbruggen** [comment]
That sounds pretty useful indeed! And perhaps something similar is possible on iOS as well (via `AFNetworking`. Are you able to take a stab at it?

**Comment by bobbyngwu** [comment]
Sure, will have a look

**Comment by bobbyngwu** [comment]
Hi Eddy, have got a PR for this, do you mind granting me permission?

**Comment by bobbyngwu** [comment]
Hi Eddy, I have a PR for this, do you mind granting me limited permission to create a branch?

**Comment by EddyVerbruggen** [comment]
Hi, there’s no need for permissions. Just fork this repo and submit a pr 👍

**Comment by bobbyngwu** [comment]
Thanks Eddy, confused this with GitLab in mind :)
