### ISSUE TITLE
Package not updated

### ISSUE THREAD

**Issue by zontafil** [nativescript-community/https#5]
I think the package in the tns plugin repo is outdated (1.0.1)

**Comment by roblav96** [comment]
@m3l7 i dont think i follow,

**Comment by zontafil** [comment]
if I download the package via npm or via tns plugin install, version 1.0.1 will be installed which I think it's an old version. 
i.e. HttpRequestOptions interface is missing url option:

    export interface HttpsRequestOptions extends HttpRequestOptions {
        method: 'GET' | 'POST';
        headers?: Headers;
        content?: string;
    }

**Comment by roblav96** [comment]
@m3l7 hmm, very strange. ill have to look into this tonight

**Comment by EddyVerbruggen** [comment]
Yes indeed, [this version](https://github.com/gethuman/nativescript-https/blob/f7d4e29b9ab85dac6dd17303e3e10400e28d4e05/https.common.d.ts) is on npm.

**Comment by roblav96** [comment]
@EddyVerbruggen my bad, i keep forgetting :X

**Comment by benzman81** [comment]
still only version 1.0.1 is in npm and not the current one :-/

**Comment by AresDev** [comment]
@roblav96 are you planning to update the package on npm anytime soon? I workaround this problem installing directly from Github repo but this is not the way that it suppose to be.
