### ISSUE TITLE
Discuss about the Body

### ISSUE THREAD

**Issue by kefahB** [nativescript-community/https#58]
Hey @EddyVerbruggen 

I want to ask you about the `Type` of the Body on this Plugin; The most common scenario to use this plugin is to migrate from `Fetch` or `http`  NS Core module to your plugin; Both of them use `HttpRequestOptions` to implement the request, and the body it `content` as `JSON.stringfy()` .. for me migrating from NS core to nativescript-https push me to change my code, of course it is not on application side but on server side, because I use PHP on the remote side and I have implemented several logic for security use.

My question it is possible to change the typing of `body` to` any` instead of `HttpsRequestObject` ?

What do you think ?

**Comment by EddyVerbruggen** [comment]
I'm not religious about the type of the body param. As long as we can remain backward compatible with older versions of the plugin I'd be happy to merge any PR.
