### ISSUE TITLE
Cannot find runtime for instance

### ISSUE THREAD

**Issue by LiamMcCallum** [nativescript-community/https#74]
Hello,

We run an Android TV app that is designed to be running for days. Unfortunately at least once a day we're seeing the following crash: 

```
com.tns.NativeScriptException: Cannot find runtime for instance=com.tns.gen.okhttp3.Callback

com.tns.Runtime.callJSMethod Runtime.java:1157
com.tns.Runtime.callJSMethod Runtime.java:1138
com.tns.Runtime.callJSMethod Runtime.java:1134
com.tns.gen.okhttp3.Callback.onResponse Callback.java:26
okhttp3.RealCall$AsyncCall.execute RealCall.java:174
okhttp3.internal.NamedRunnable.run NamedRunnable.java:32
java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1167
```

This usually happens after at least a few hours running, sometimes days.

Any ideas?

Thanks,
Liam

**Comment by farfromrefug** [comment]
@LiamMcCallum you should search on okhttp repo. You ll have better chances to find the root of the issue there.

**Comment by LiamMcCallum** [comment]
Thanks @farfromrefug. Do you mean ask on https://github.com/square/okhttp/issues? It seems the only errors I see are related to NativeScript unable to find the runtime for com.tns.gen.okhttp3.Callback. I'm not quite sure what I'd ask them that wasn't related to NativeScript.

**Comment by farfromrefug** [comment]
But wait I am dumb ! It is us :) sorry. 
It happens randomly?
Do you have the js code that triggers that ?

**Comment by LiamMcCallum** [comment]
Hi @farfromrefug. No unfortunately not. It runs for days without issue in our offices, but we see some basic crash logs through Microsoft App Center (only the above slim info). I can tell you it takes hours/days before the app finally crashes. Feel free to close this for now, but if you think of any ideas please let us know!
