### ISSUE TITLE
[iOS] Content/body not sent using POST

### ISSUE THREAD

**Issue by sivo1981** [nativescript-community/https#75]
Bellow code is working fine on Android, but on iOS content / body is not sent to the server.

```
const response = await Https.request({
  useLegacy: true,
  method: 'POST',
  url: `${baseUrl}${url}`,
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
  },
  content: stringify(body),
})
```

Tried with `useLegacy=false`  and `useLegacy=false` and there is no difference.

Using latest version of NS7 and HTTPS.

Any ideas?

**Comment by farfromrefug** [comment]
@sivo1981 try to use `body:body` instead of `content: stringify(body)` . This is what i do

**Comment by sivo1981** [comment]
@farfromrefug Thanks for the hint. Meanwhile i have found out that maually setting cookie to header (aka. remember-me) also doesnt work as i expected, so i switched to axios.
