### ISSUE TITLE
Demo doesn't run, fails after tsc -skipLibCheck with errors

### ISSUE THREAD

**Issue by SylvatiCodes** [nativescript-community/https#78]
What's the best way of showing the log file (it's about 120 lines so rather big for pasting raw into here)?

Tried to `npm run demo.android`  (and the same for ios). Also tried `npm run build` to go through step by step. Errors on 
```sh
https.android.ts:11:23 - error TS2503: Cannot find namespace 'java'.

11     x509Certificate?: java.security.cert.Certificate;
                         ~~~~
```
initially, but with 112 other similar errors showing cannot find name 'okhttp3' and others.

**Comment by farfromrefug** [comment]
@PatrickLohan my bad there was an issue with the remote origin of my local setup. I pushed everything now and it should work now

**Comment by SylvatiCodes** [comment]
No worries thanks for the speediness!

Tried again but getting this error now (without the masses of namespace errors as before):
```
...
> cp src/https.d.ts plugin && tsc -skipLibCheck -d

The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nativescript-community/https@1.0.0 demo.android: `npm run build && cd ../demo && tns run android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nativescript-community/https@1.0.0 demo.android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
```
with the path to the log file after this output.

**Comment by farfromrefug** [comment]
OK think something is wrong with the demo script. run `npm run build` then go into the demo dir and run it

**Comment by SylvatiCodes** [comment]
Hi again, tracked it down to relative paths being incorrect. Have fixed and made a PR. You can now just `cd https` and `npm run demo.android` or, presumably, ios. High five!
