### ISSUE TITLE
HttpsRequestOptions body field vs. HttpRequestOptions content field

### ISSUE THREAD

**Issue by andy-tai** [nativescript-community/https#9]
The HttpsRequestOptions object seems to be modelled after NativeScript's built in HttpRequestOptions object, as seen from the example in the documentation.  However, in the current code the "content" field of HttpsRequestOptions is actually named "body" so the example code as is would not work.

**Comment by roblav96** [comment]
@andy-tai Ah yes, that is entirely true :X 

I do plan on revamping the crap out of this plugin for nativescript v3

**Comment by chuckmitchell** [comment]
> nativescript v3
